#!/usr/bin/env python

import argparse
import logging

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", required=True, help="input path")
parser.add_argument("-l", "--logging", action="store_true", help="turns logging on")
args = parser.parse_args()

def logger(indata):
    #creating a log file that messages will be printed to
    logging.basicConfig(filename='example.log', level=logging.DEBUG)
    #logging.debug('This messages will show up in the log file')
    #logging.info('so will this')
    #logging.warning('and this')
    logging.debug(indata)

#def mainlog():
    #blah blah

def main(input_data):
    infile=open(input_data)
    stored_input = infile.readlines()
    if args.logging:
        for entry in stored_input:
            print(entry)
            logger(entry)
    else:
        for entry in stored_input:
            print(entry)

main(args.input)
