#!/bin/env python

import numpy as np
import matplotlib.pyplot as plt

#plt.plot([1,2,3,4])
#plt.ylabel('some numbers')
#plt.show

#plt.plot([1,2,3,4], [1,4,9,14], 'ro')
#plt.axis([0,6,0,20])
#plt.show()

t = np.arange(0.,5.,0.2)

plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^')
plt.show()

plt.plot(x, y, linewidth=2.0)
