#!/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import random as r

plt.plot([1,2,3,4,5,6,7,8], [r.randint(1,10),r.randint(1,10),r.randint(1,10),r.randint(1,10),r.randint(1,10),r.randint(1,10),r.randint(1,10),r.randint(1,10)])

plt.show()
