#!/usr/bin/env python

import sys

infile = open(sys.argv[1], "r")

for i,line in enumerate(infile):
    print("\nSample No.", i, "\n")
    line = line.split("\t")
    #print(line)
    for value in line:
        value = value.split(",")
        print(value[0])
