#!/usr/bin env python

import argparse
import os.path

def is_valid_file(parser, arg):
    if not os.path.exists(arg):
        parser.error("The file %s does not exist!" %arg)
    else:
        return open(arg, 'r')

parser = argparse.ArgumentParser()
parser.add_argument("-p", "--findp", action="store_true")
parser.add_argument("-i", dest="filename", required=True,
                    help="input file", metavar="FILE",
                    type=lambda x: is_valid_file(parser, x))
args = parser.parse_args()

a = open(args.filename)

for line in a:
    print(line)


