#!/usr/bin/env python

#use lambda to sort by line[6] in tab delimited fields in a text file.

import sys 

def main():
    infile = open(sys.argv[1],'r').readlines()
    lines = [line.split("\t") for line in infile]
    for line in lines:
        line[-1] = line[-1].rstrip()
        diff = str(int(line[2])-int(line[1]))
        line.append(diff)
    sline = sorted(lines, key=lambda line:line[-1], reverse = True)
    for line in sline:
        line = "\t".join(line)
        print(line)

main()
        
