#!/usr/bin/env python

import sys

def main():
   infile = open(sys.argv[1],'r')
   for line in infile:
       if line == "\n":
           pass
       else:
           line = line.split("\t")
           line[5] = line[5].rstrip()
           print("\t".join(line))

main()
