#!/bin/env python

import pysam
import sys

samples1_path=open(sys.argv[5], 'r')
samples2_path=open(sys.argv[6], 'r')

def generate_samples(path):
    samples_list=[]
    for bam in path:
        bam=bam.rstrip()
        samples_list.append(pysam.Samfile(bam, "rb"))
    return(samples_list)

def getreads(chrom, start, end, cutoff, sample):
    #cutoff = sys.argv[3:
    acceptablereads=[]
    for i,infile in enumerate(sample):
        #print("\nReads for sample", i, ": ")
        total = []
        #debug print
        for j,read in enumerate((infile.fetch(sys.argv[1], int(sys.argv[2]), int(sys.argv[3])))):
            total.append(j)
        readcount = len(total)
        if (readcount > cutoff) or (readcount == cutoff):
            #print whole line from lobstr compare output?
            acceptablereads.append(read)
        else:
            pass
    return(acceptable_reads)

samples1=generate_samples(samples1_path)
samples2=generate_samples(samples2_path)

print("\nGroup 1 :")
getreads(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4], samples1)
print("\nGroup 2 :")
getreads(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4], samples2)
