#!/usr/bin/env bash 

for file in $(find /home/xiavan/Data/lobSTRdata/exomedata/affected_bams/unindexed/ -type f)
do
    #abspath has to be manually entered because im feeling lazy
    abspath="/home/xiavan/Data/lobSTRdata/exomedata/affected_bams/unindexed/"
    NAME=($(basename $file))
    outsuffix=".bai"
    outname=$abspath$NAME$outsuffix
    echo "Indexing $NAME"
    samtools index $file $outname
    echo "Indexing completed."
done

for file in $(find /home/xiavan/Data/lobSTRdata/exomedata/unaffected_bams/unindexed/ -type f)
do
    #abspath has to be manually entered because im feeling lazy
    abspath="/home/xiavan/Data/lobSTRdata/exomedata/unaffected_bams/unindexed/"
    NAME=($(basename $file))
    outsuffix=".bai"
    outname=$abspath$NAME$outsuffix
    echo "Indexing $NAME"
    samtools index $file $outname
    echo "Indexing completed."
done
